apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: databases
resources:
  - namespace.yml
  - pg-cluster.yml

secretGenerator:
  - name: database-creds
    options:
      disableNameSuffixHash: true
    literals:
      - username=app
      - password=1f2d1e2e67df
    type: kubernetes.io/basic-auth


# this project is a test of Cloud Native PostgreSQL
# it is not intended for production use