apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0
  storage:
    size: 2Gi
  bootstrap:
    initdb:
      database: app
      owner: app
      dataChecksums: true
      encoding: UTF8
      secret:
        name: database-creds
  backup:
    retentionPolicy: 7d
    volumeSnapshot:
      className: standard
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: preferred
