apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: database-creds
